# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b50beb265e9a9b88c88063e6c6d6cb02690d539cf450ae96b47f61e7155bff5f6797d0b31f695dd4b4204f834c976e4482bf41c30491230132d359319e3bafb3

test:
  secret_key_base: fcdd437fd9c71569c5bb06ec54710a83042f1250fa683025542be6dced7e5d945156d4c13508b61a2edeacab05e0f914fc4337379c79f6ffeeb7f7076b71808c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
